import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request'
import BlogCard from '../components/BlogCard'




const graphcms = new GraphQLClient(
  "https://api-ap-south-1.graphcms.com/v2/cl3u8j6vsdl2a01xi9yfwhpxh/master"
)
const QUERY = gql` 
{
    posts{
    id, 
    title,
    date_published,
    slug,
    content{
        html
      }
      author{
        name 
        avatar{
          url
        }
      }
      coverPhoto{
        url 
      }
       publishedBy{
        name
      }
    }
}
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  }
}

export default function Home({ posts }) {




  return (
    <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map(post => (
          <BlogCard
            key={post.id}
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            datePublished={post.date_published}
            slug={post.slug}
          />
        ))}
      </main>
    </div>
  )
}
